set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'jiangmiao/auto-pairs'
Plug 'editorconfig/editorconfig-vim'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'ziglang/zig.vim'
Plug 'bellinitte/uxntal.vim'
Plug 'tikhomirov/vim-glsl'
Plug 'lluchs/vim-wren'
Plug 'boltlang/vim-bolt'
call plug#end()

set runtimepath+=/opt/homebrew/opt/fzf
set runtimepath+=/opt/homebrew/share/fzf/.vim

set backspace=indent,eol,start
set hidden
set magic
set noswapfile
set nofoldenable
set lazyredraw
set mouse=a

set ignorecase
set smartcase
set incsearch
set hlsearch
set showmatch

set laststatus=2
set scrolloff=3
set sidescroll=3
set ruler
set cc=80
set nowrap
set splitbelow
set notimeout

set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set smartindent
set clipboard=unnamed

let mapleader = "\<space>"

nnoremap <C-p> :FZF<CR>
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>l :Lines<CR>
nnoremap <leader>h :History:<CR>

nnoremap \\ :noh<cr> 
nnoremap <silent> <F5> :let _s=@/<Bar>:%s/\s\+$//e<Bar>:let @/=_s<Bar>:nohl<CR>
nnoremap Y y$
nnoremap cc :center<cr>
inoremap <C-c> <ESC>

set listchars=tab:▸\ ,eol:¬,space:.
nnoremap <leader>w :set list!<CR>
vnoremap Hs :sort /[^;]*/ r<CR>

autocmd FileType c,cpp,objc,objcpp setlocal noexpandtab shiftwidth=8 tabstop=8 softtabstop=8
autocmd FileType markdown setlocal tw=80 et ts=2 sw=2
autocmd FileType text setlocal tw=80

syntax on
set background=dark
colorscheme default
set notermguicolors

set number
set relativenumber
set cursorline

highlight Normal       ctermfg=NONE ctermbg=NONE
highlight PreProc      cterm=bold ctermfg=15 ctermbg=NONE
highlight Include      cterm=bold ctermfg=15 ctermbg=NONE
highlight Define       cterm=bold ctermfg=15 ctermbg=NONE
highlight Type         cterm=bold ctermfg=15 ctermbg=NONE
highlight StorageClass cterm=bold ctermfg=15 ctermbg=NONE
highlight Structure    cterm=bold ctermfg=15 ctermbg=NONE
highlight Typedef      cterm=bold ctermfg=15 ctermbg=NONE

highlight Statement    cterm=bold ctermfg=3  ctermbg=NONE
highlight Conditional  cterm=bold ctermfg=3  ctermbg=NONE
highlight Keyword      cterm=bold ctermfg=3  ctermbg=NONE
highlight Operator     cterm=bold ctermfg=3  ctermbg=NONE

highlight String       cterm=NONE ctermfg=14 ctermbg=NONE
highlight cIncluded    cterm=NONE ctermfg=14 ctermbg=NONE
highlight Number       cterm=NONE ctermfg=11 ctermbg=NONE
highlight Constant     cterm=NONE ctermfg=11 ctermbg=NONE
highlight Boolean      cterm=NONE ctermfg=11 ctermbg=NONE

highlight Identifier   cterm=NONE ctermfg=7  ctermbg=NONE
highlight Delimiter    cterm=NONE ctermfg=8  ctermbg=NONE
highlight Comment      cterm=italic ctermfg=8 ctermbg=NONE

highlight LineNr       cterm=NONE ctermfg=8  ctermbg=NONE
highlight CursorLine   cterm=NONE ctermbg=0  ctermfg=NONE
highlight CursorLineNr cterm=bold ctermfg=15 ctermbg=NONE
highlight Visual       cterm=reverse ctermfg=NONE ctermbg=NONE
highlight ColorColumn  ctermbg=0 guibg=#111111
